# Welcome to Agency Jekyll Theme!

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: "#jonandgabi2019" 
email: jsonesen@gmail.com 
description: > # this means to ignore newlines until "author:"
    We gettin married y'all!
author: Jon Sonesen 
keyword: jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: st4nkw1z 

# Build settings

markdown: kramdown

# theme: agency-jekyll-theme
# the "agency-jekyll-theme" is not supported by GitHub Pages. 

gems:
  - jekyll-feed
exclude:
  - agency-jekyll-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
